// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"特定のアイテムと交換を行うショップ","status":true,"description":"メダルや貝殻など、特定のアイテムをお金の代わりに使えるショップを作成することができます","parameters":{"tradeShopSwitchId":"13","tradeItemId":"218","tradeItemTanni":"個"}},
{"name":"SlotMachine","status":true,"description":"Slot Machine scene","parameters":{"Variable ID":"11","Help Text":"カーソルキーの上でベット、カーソルキーの下でスタート","Won Text":"おめでとうございます！Win Coin枚獲得です！","Lost Text":"残念でした。","Replay Text":"もう一度やりますか？","Coin Full Text":"コイン枚数が制限に達しました。","Bet Text":"ベット","Spin Text":"スピン","Yes Text":"はい","No Text":"いいえ"}},
{"name":"TouchUI","status":true,"description":"UIをタッチ操作に適したものへ変更します。","parameters":{"Menu Command Text":"メニュー","Previous Command Text":"前","Next Command Text":"次"}},
{"name":"TMBackButton","status":true,"description":"メニューシーンにタップ操作用の戻るボタンを表示します。","parameters":{"buttonImage":"backButton","sceneMenuX":"100","sceneMenuY":"400","sceneItemX":"600","sceneItemY":"50","sceneSkillX":"140","sceneSkillY":"250","sceneEquipX":"200","sceneEquipY":"100","sceneStatusX":"400","sceneStatusY":"30","sceneOptionsX":"380","sceneOptionsY":"400","sceneSaveX":"500","sceneSaveY":"14","sceneLoadX":"500","sceneLoadY":"14","sceneGameEndX":"0","sceneGameEndY":"0","sceneShopX":"600","sceneShopY":"20","sceneNameX":"20","sceneNameY":"200"}},
{"name":"歩数減算","status":true,"description":"歩数を調整するプラグインです","parameters":{}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"-200","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"TYA_EnemyHPGauge","status":true,"description":"敵ターゲットウィンドウにＨＰゲージを表示させます。\r\n特定の敵のゲージを非表示にすることもできます。","parameters":{}},
{"name":"TMMapNameEx","status":true,"description":"マップ名の表示を調整し、一部の制御文字に対応します。","parameters":{"windowX":"200","windowY":"280","windowWidth":"360","windowLineHeight":"96","fontFace":"GameFont","fontSize":"28"}},
{"name":"Chronus","status":true,"description":"ゲーム内時間の導入プラグイン","parameters":{"月ごとの日数配列":"31,28,31,30,31,30,31,31,30,31,30,31","月名配列":"Jan.,Feb.,Mar.,Apr.,May.,Jun.,Jul.,Aug.,Sep.,Oct.,Nov.,Dec.","曜日配列":"(日),(月),(火),(水),(木),(金),(土)","自然時間加算":"5","自然時間加算間隔":"60","場所移動時間加算":"0","戦闘時間加算(固定)":"30","戦闘時間加算(ターン)":"5","年のゲーム変数":"0","月のゲーム変数":"0","日のゲーム変数":"0","曜日IDのゲーム変数":"0","曜日名のゲーム変数":"0","時のゲーム変数":"0","分のゲーム変数":"0","累計時間のゲーム変数":"0","累計日数のゲーム変数":"0","時間帯IDのゲーム変数":"0","天候IDのゲーム変数":"0","フォーマット時間の変数":"0","フォーマット時間の計算式":"HH24 * 60 + MI","日時フォーマット1":"YYYY年 MM月 DD日 DY","日時フォーマット2":"AMHH時 MI分","カレンダー表示X座標":"0","カレンダー表示Y座標":"0","カレンダーフォントサイズ":"0","カレンダー不透明度":"192","カレンダー余白":"8","文字盤画像ファイル":"","長針画像ファイル":"","短針画像ファイル":"","時計X座標":"740","時計Y座標":"78","イベント中時間経過":"false"}},
{"name":"ChangeWeaponOnBattle","status":true,"description":"戦闘コマンドに装備変更を追加","parameters":{"commandName":"装備変更"}}
];
